theme = "nord"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
cursorline = true
rulers = [120]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
charater = "|"
render = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["version-control"]
separator = "||"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[keys.insert]
"C-c" = "normal_mode"
